// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageType.proto

#ifndef PROTOBUF_messageType_2eproto__INCLUDED
#define PROTOBUF_messageType_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_messageType_2eproto();
void protobuf_AssignDesc_messageType_2eproto();
void protobuf_ShutdownFile_messageType_2eproto();


enum eMessageType {
  TypeC2SLoginReq = 1
};
bool eMessageType_IsValid(int value);
const eMessageType eMessageType_MIN = TypeC2SLoginReq;
const eMessageType eMessageType_MAX = TypeC2SLoginReq;
const int eMessageType_ARRAYSIZE = eMessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* eMessageType_descriptor();
inline const ::std::string& eMessageType_Name(eMessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    eMessageType_descriptor(), value);
}
inline bool eMessageType_Parse(
    const ::std::string& name, eMessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<eMessageType>(
    eMessageType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::eMessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::eMessageType>() {
  return ::eMessageType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messageType_2eproto__INCLUDED
